name: Gradle Nightly Check

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 1,4'

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 14
      JDK_BUILD: 14
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: |
        printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
        curl -LfSo ./openjdk.tar.gz "https://download.java.net/java/early_access/jdk${JDK_VERSION}/${JDK_BUILD}/GPL/openjdk-${JDK_VERSION}-ea+${JDK_BUILD}_linux-x64_bin.tar.gz"
      - uses: actions/setup-java@v1
        with:
          java-version: 14
          architecture: x64
          jdkFile: ./openjdk.tar.gz
      - run: java --version
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: nightly
          arguments: check  -PtargetJava=14 --warning-mode=all --stacktrace

