name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 12
#      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --stacktrace

      - name: Bintray Publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_GPG_PASSPHRASE: ${{ secrets.BINTRAY_GPG_PASSPHRASE }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :pagerduty-event-json-iterator-adapter:bintrayUpload :pagerduty-event-client:bintrayUpload
        if: success() && github.event_name == 'create'


